// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKjiPSs9HDut1r23YkgxlDgNluuXNn87Y',
    appId: '1:102630465950:android:fa13873f6060852daa768f',
    messagingSenderId: '102630465950',
    projectId: 'beontime-cfd0d',
    databaseURL: 'https://beontime-cfd0d.firebaseio.com',
    storageBucket: 'beontime-cfd0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Ds-U2ad_8fQzT5rBmqMIuxrVKIg0MpI',
    appId: '1:102630465950:ios:27935fb28890ff12aa768f',
    messagingSenderId: '102630465950',
    projectId: 'beontime-cfd0d',
    databaseURL: 'https://beontime-cfd0d.firebaseio.com',
    storageBucket: 'beontime-cfd0d.appspot.com',
    androidClientId: '102630465950-71tq28ju79qpgev5g51k0h5le7nsc6ln.apps.googleusercontent.com',
    iosBundleId: 'com.itufuturz.happyhearts',
  );
}
